### ISSUE TITLE
Make Hover Styles of Player + Purchase Components Configurable via Props

### ISSUE THREAD

**Issue by abelsonlive** [gltd/releases#36]
Hover styles are currently broken, but better than being invisible. Let's make these configurable so we can customize each site.

**Comment by jak2030** [comment]
What configuration are you thinking?

**Comment by jak2030** [comment]
Oh just colors?

**Comment by abelsonlive** [comment]
the colors and the hover styles, which is kinda complicated in React I think:

https://stackoverflow.com/questions/28365233/inline-css-styles-in-react-how-to-implement-ahover
