### ISSUE TITLE
Figure out sane way of handling Web Audio API quirks

### ISSUE THREAD

**Issue by abelsonlive** [gltd/releases#38]
We should have a class which handles all the Web Audio API edge cases for us so this logic doesn't seep its way into the Release Components. Maybe we could patch `howler` to work with the Web Audio API?

**Comment by jak2030** [comment]
howler "Defaults to Web Audio API and falls back to HTML5 Audio" - I think we are depending on HTML5 Audio to capture stream and use the analyser?

**Comment by abelsonlive** [comment]
yeah, that's right. i'm wondering if going full web audio api would be better.
