### ISSUE TITLE
Releases page

### ISSUE THREAD

**Issue by jak2030** [gltd/releases#40]
We need a releases page.

In turn, this can potentially free up the menu page to be re-purposed for potentially multiple tracks on a given release page.

My current idea for a release page is to have a full text search bar on top of page that filters clickable bubbles where each bubble links to a release -->

https://threejs.org/examples/webgl_materials_shaders_fresnel.html

**Comment by abelsonlive** [comment]
yeah! this would be cool. I wonder if we could shade the bubbles with a screenshot of the sites so it's like a preview of what you'll see.
